### ISSUE TITLE
npm t && npm run build giving following error

### ISSUE THREAD

**Issue by yogeshwar607** [eggheadio-github/stack-overflow-copy-paste#27] opened 2016-06-09 22:41 UTC
ava --require babel-register

sh: ava: command not found
npm ERR! Test failed.  See above for more details.

Note npm version : 3.9.5

**Comment by kentcdodds** [comment] 2016-06-09 22:42
Hi @yogeshwar607, did you first run `npm install`?

**Comment by yogeshwar607** [comment] 2016-06-09 22:43
yes

**Comment by yogeshwar607** [comment] 2016-06-09 22:46
<img width="1280" alt="screen shot 2016-06-10 at 4 14 25 am" src="https://cloud.githubusercontent.com/assets/10059011/15949010/f143abe2-2ec1-11e6-8ca5-4d57093b4938.png">
<img width="1280" alt="screen shot 2016-06-10 at 4 14 12 am" src="https://cloud.githubusercontent.com/assets/10059011/15949012/f341cdac-2ec1-11e6-9636-cca778bd4f21.png">

**Comment by kentcdodds** [comment] 2016-06-09 23:18
Hmmm... Could you look in your `node_modules/.bin/` directory and see if there's an `ava` file in there?

**Comment by sourabhswain** [comment] 2016-08-10 08:22
@kentcdodds  Hello I am also facing an error when running npm t && npm run build on Windows. Could you please help me ? Thanks.

npm ERR! Test failed.  See above for more details.

![error](https://cloud.githubusercontent.com/assets/6239837/17546835/971c1300-5f01-11e6-9050-19a434df5871.png)

**Comment by kentcdodds** [comment] 2016-08-10 12:37
Hmmm... I'm not certain what the issue is. I've just pushed an update to all the dependencies. Could you try again with the latest changes? If you get the same error message, I think the issue is with the `cross-spawn` lib. You might try digging in there to find what the problem could be. Good luck!

**Comment by mtheoryx** [comment] 2016-08-11 23:45
Unable to replicate on a completely fresh checkout, npm install and then npm run build.

Mac OS 10.10.5
Node v4.4.0
npm 2.14.20

I suggest closing for now unless reporter wants to reopen with some more details of environment that could help track down the issue. The reporter should get a notification that their issue was closed, and would then have the opportunity to respond. Middle-of-the-road solution, but doesn't leave issues open that can't be acted upon.

**Closed** 2016-08-12 01:12 UTC

**Comment by naumicoder** [comment] 2016-12-22 12:59
I was also getting the same error and came across this question. Upgrading the Node.js version easily solved my problem.
