### ISSUE TITLE
 404 Not Found: @semantic-release/commit-analyzer@^2.0.0

### ISSUE THREAD

**Issue by wsierakowski** [eggheadio-github/stack-overflow-copy-paste#127] opened 2017-11-04 11:07 UTC
Perhaps this is not an issue with this project but rather with one of its dependencies but I would still want to check if I understand what the root cause is.

When I'm trying to npm install stack-overflow-copy-paste, I'm getting this error: 

>  `404 Not Found: @semantic-release/commit-analyzer@^2.0.0`

When I go and check the semantic-release own github repository and package.json I can see they have this line in their dependencies (https://github.com/semantic-release/semantic-release/blob/caribou/package.json): 

> `"@semantic-release/commit-analyzer": "^4.0.0"`

So first I thought that perhaps the problem is that stack-overflow-copy-paste depends on an older and unsupported version of the semantic release - this is the line from your package.json:

> "semantic-release": "4.3.5",

But even if I try to install the latest version, I'm still getting an error about commit-analyzer 2.0.0.

I'm not quite sure how to fix this problem.

Does anyone else sees the same error?

My npm version is: 5.5.1
Node: 8.7.0

**Comment by wsierakowski** [comment] 2017-11-04 11:12
Just a clarification, when I attempt to install the latest version of semantic-release: 8.2.0, I'm getting the following error now:

> `404 Not Found: @semantic-release/commit-analyzer@^3.0.1`

Note that the version of commit-analyzer dependency is different.

**Comment by kentcdodds** [comment] 2017-11-06 02:53
Hi @wsierakowski! I'm not sure I understand.

Are you saying you're getting the error when trying to run `npm install stack-overflow-copy-paste` or when running `npm install` inside the directory where you cloned the `stack-overflow-copy-paste` repo. In either case I was unable to reproduce your issue. Try again?

**Comment by kentcdodds** [comment] 2017-11-06 02:53
Because I'm unable to reproduce the issue, I'll go ahead and close this, but if you could dig a little more that'd be great. Good luck!

**Closed by kentcdodds** 2017-11-06 02:53 UTC
